<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $expenses = [
            [
                'name' => 'CVPS-4 - host.sweet.web.id',
                'amount' => 590000.00,
                'currency' => 'IDR',
                'provider' => 'Awan Data',
                'category' => 'Server',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CloudLinux',
                'amount' => 335000.00,
                'currency' => 'IDR',
                'provider' => 'Awan Data',
                'category' => 'Server',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Softaculous License',
                'amount' => 29000.00,
                'currency' => 'IDR',
                'provider' => 'Awan Data',
                'category' => 'Server',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DirectAdmin',
                'amount' => 95000.00,
                'currency' => 'IDR',
                'provider' => 'Awan Data',
                'category' => 'Server',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Imam',
                'amount' => 2450000.00,
                'currency' => 'IDR',
                'provider' => 'Websweet Studio',
                'category' => 'Gaji',
                'next_billing' => '2025-09-30',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'one-time',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Claude',
                'amount' => 341000.00,
                'currency' => 'IDR',
                'provider' => 'Antropic',
                'category' => 'AI',
                'next_billing' => '2025-10-05',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TRAE',
                'amount' => 180000.00,
                'currency' => 'IDR',
                'provider' => 'Trae',
                'category' => 'AI',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Listrik',
                'amount' => 250000.00,
                'currency' => 'IDR',
                'provider' => 'PLN',
                'category' => 'Kantor',
                'next_billing' => '2025-10-01',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'cPGuard',
                'amount' => 180000.00,
                'currency' => 'IDR',
                'provider' => 'Opshield',
                'category' => 'Server',
                'next_billing' => '2025-10-10',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Internet',
                'amount' => 275000.00,
                'currency' => 'IDR',
                'provider' => 'MyRepublic',
                'category' => 'Kantor',
                'next_billing' => '2025-10-15',
                'paid_date' => null,
                'status' => 'active',
                'type' => 'monthly',
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        \App\Models\Expense::insert($expenses);
    }
}
